import QtQuick
import Quickshell
import qs.features.bar.ui
import qs.features.capture.ui
import qs.features.clipboard.ui
import qs.features.dashboard.ui
import qs.features.displays.ui
import qs.features.energy.ui
import qs.features.idle.ui
import qs.features.input.ui
import qs.features.launcher.ui
import qs.features.lockscreen.ui
import qs.features.nightlight.ui
import qs.features.notifications.ui
import qs.features.osd.ui
import qs.features.powerMenu.ui
import qs.features.settings.ui
import qs.features.sidebar.ui
import qs.features.themeSwitcher.ui
import qs.features.wallpaper.ui

ShellRoot {
    Wallpaper {}
    Bar {}
    CaptureOverlay {}
    Clipboard {}
    Dashboard {}
    Displays {}
    Energy {}
    Idle {}
    Input {}
    Launcher {}
    NightLight {}
    NotificationPopups {}
    Osd {}
    PowerMenu {}
    Settings {}
    MonitorConfirm {}
    MonitorIdentify {}
    Sidebar {}
    Lockscreen {}
    ThemeSwitcher {}
}
